server:
  port: 8000
spring:
  application:
    name: short-link-gateway
  data:
    redis:
      host: 192.168.29.130
      port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: short-link-admin
          uri: lb://short-link-admin
          predicates:
            - Path=/api/short-link/admin/**
          filters:
            - name: TokenValidate
              args:
                whitePathList:
                  - /api/short-link/admin/v1/user/login
                  - /api/short-link/admin/v1/user/has-username
        - id: short-link-project
          uri: lb://short-link-project/
          predicates:
            - Path=/api/short-link/**
          filters:
            - name: TokenValidate
  devtools:
    livereload:
      port: 35730
