server:
  port: 8010

spring:
  application:
    name: short-link-project
  devtools:
    livereload:
      port: 35731
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: 192.168.29.130
      port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  rabbitmq:
    host: 192.168.29.130
    username: dym
    password: 775821
    port: 5672
mybatis-plus:
  global-config:
    banner: off
  mapper-locations: classpath:mapper/*.xml
short-link:
  domain:
    default: nurl.ink:${server.port}
  stats:
    locale:
      amap-key: 326b6e33a6347c39a52dc40570e4d011
  goto-domain:
    white-list:
      enable: true
      names: '拿个offer,知乎,掘金,博客园'
      details:
        - nageoffer.com
        - zhihu.com
        - juejin.cn
        - cnblogs.com
